compressionLevel: mixed

enableGlobalCache: false

enableImmutableInstalls: false

npmPublishAccess: public

packageExtensions:
  "@swc-node/sourcemap-support@*":
    dependencies:
      tslib: "*"
  css@*:
    dependencies:
      fs: "*"
  debug@*:
    dependencies:
      supports-color: "*"
  dynamodb-toolbox@*:
    dependencies:
      "@aws-sdk/util-dynamodb": "*"
  express@*:
    dependencies:
      ejs: "*"
  webpack@*:
    peerDependencies:
      webpack-cli: "*"

yarnPath: .yarn/releases/yarn-4.2.2.cjs
