name: Deploy shalveena.com
run-name: Deploy shalveena.com by ${{ github.actor }} 🚀
on:
  push:
    branches:
      - master

jobs:
  build:
    name: '✈️ Deploy Shalveena Blog'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/goldstack-setup
      - run: |
          cd packages/web-shalveena-com
          yarn deploy dev
          yarn deploy prod
    env:
      AWS_USER_NAME: awsUser
      AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
      AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}
      AWS_DEFAULT_REGION: us-west-2
